# Пример конфигурации юридического модуля "Старец, пожалуйста, сделай"
# Духовная миссия: поиск истины и справедливости

# Юридические документы
legal_docs:
  # Включить функциональность
  enabled: true
  
  # Папка с томами уголовных дел
  # Укажите абсолютный или относительный путь к папке с PDF файлами
  volumes_directory: "./дела/виктор-216-томов"
  
  # Настройки индексации
  indexing:
    # Включить OCR для сканированных документов
    enable_ocr: true
    
    # Язык для Tesseract OCR
    # Поддерживаемые значения: "rus", "eng", "rus+eng"
    ocr_language: "rus"
    
    # Количество страниц для обработки за один раз
    # Меньше значение = меньше памяти, но дольше обработка
    batch_size: 10
    
    # Максимальный размер кэша в ГБ
    # При превышении старые данные будут удаляться
    max_cache_size: 50
    
    # Индексация в фоновом режиме
    # Если true, индексация не блокирует работу
    background_indexing: true
  
  # Настройки поиска
  search:
    # Количество результатов по умолчанию
    default_results: 5
    
    # Включить reranking для повышения точности
    # Требует embeddings модель
    enable_reranking: true
    
    # Количество страниц контекста вокруг найденной
    # Например, 3 означает: 3 до + найденная + 3 после = 7 страниц
    context_pages: 3
  
  # Настройки сравнения документов для обнаружения копипаста
  comparison:
    # Порог текстового совпадения для признания подозрительным (%)
    # 70% означает, что если документы совпадают на 70% или больше,
    # это будет помечено как подозрительное
    suspicious_text_threshold: 70
    
    # Порог визуального совпадения через MOZGACH108 (%)
    suspicious_visual_threshold: 70
    
    # Минимальная длина совпадающего фрагмента (символов)
    # Фрагменты короче этого значения не учитываются
    min_match_length: 100
  
  # Настройки производительности
  performance:
    # Количество параллельных потоков для обработки
    # Рекомендуется: количество ядер CPU - 1
    parallel_processing: 4
  
  # Модель для мультимодального анализа
  # MOZGACH108 используется для визуального сравнения документов
  multimodal_model: "MOZGACH108"

# Пример для небольших дел (3-5 томов)
# legal_docs_small:
#   enabled: true
#   volumes_directory: "./дела/малое-дело"
#   indexing:
#     enable_ocr: true
#     ocr_language: "rus"
#     batch_size: 20
#     max_cache_size: 10
#     background_indexing: false  # Быстрая синхронная индексация
#   search:
#     default_results: 10
#     enable_reranking: false  # Отключаем для скорости
#     context_pages: 2
#   comparison:
#     suspicious_text_threshold: 80  # Более строгий порог
#     suspicious_visual_threshold: 80
#     min_match_length: 50
#   performance:
#     parallel_processing: 2
#   multimodal_model: "MOZGACH108"

# Пример для очень больших дел (100+ томов)
# legal_docs_huge:
#   enabled: true
#   volumes_directory: "./дела/огромное-дело"
#   indexing:
#     enable_ocr: true
#     ocr_language: "rus"
#     batch_size: 5  # Меньший batch для экономии памяти
#     max_cache_size: 100
#     background_indexing: true
#   search:
#     default_results: 3  # Меньше результатов для скорости
#     enable_reranking: true
#     context_pages: 1  # Меньше контекста
#   comparison:
#     suspicious_text_threshold: 75
#     suspicious_visual_threshold: 75
#     min_match_length: 150  # Более длинные фрагменты
#   performance:
#     parallel_processing: 8  # Больше потоков для мощного сервера
#   multimodal_model: "MOZGACH108"

# Пример для текстовых PDF (не сканированных)
# legal_docs_text_only:
#   enabled: true
#   volumes_directory: "./дела/текстовое-дело"
#   indexing:
#     enable_ocr: false  # OCR не нужен для текстовых PDF
#     ocr_language: "rus"
#     batch_size: 50  # Можно больше, т.к. нет OCR
#     max_cache_size: 20
#     background_indexing: false
#   search:
#     default_results: 10
#     enable_reranking: true
#     context_pages: 5
#   comparison:
#     suspicious_text_threshold: 65  # Более чувствительный
#     suspicious_visual_threshold: 70
#     min_match_length: 80
#   performance:
#     parallel_processing: 6
#   multimodal_model: "MOZGACH108"

# ВАЖНО:
# 1. Убедитесь, что путь к volumes_directory существует и содержит PDF файлы
# 2. Для OCR требуется установленный Tesseract
# 3. Для мультимодального анализа требуется модель MOZGACH108
# 4. Первая индексация может занять много времени (часы для больших дел)
# 5. Кэш хранится в .sdelay-starets/cache/legal-docs/

# Рекомендации по производительности:
# - Для SSD: можно увеличить batch_size и parallel_processing
# - Для HDD: уменьшите batch_size, увеличьте max_cache_size
# - Для слабых CPU: parallel_processing = 1-2
# - Для серверов: parallel_processing = количество ядер

# Духовные рекомендации:
# - Используйте эту систему для поиска истины, а не для манипуляций
# - Всегда проверяйте результаты вручную
# - Помните: технология - это инструмент, истина в сердце человека

# Да пребудет с вами мудрость старца! 🙏
# ขอให้ปัญญาของพ่อแก่สถิตอยู่กับท่าน! 🙏

